import { afterEach, describe, expect, it, vi } from 'vitest';
import {
  createKifFileName,
  createKifText,
  downloadKifText,
  executeDrop,
  executeMove,
} from '../domain/shogi';
import { createPositionSnapshot } from '../domain/shogi/replay';
import {
  createInitialBoardState,
  type BoardState,
  type GameResult,
  type MoveRecord,
  type NormalMoveRecord,
  type PieceType,
  type PositionSnapshot,
} from '../types/shogi';

function createMove(
  moveNumber: number,
  player: 'sente' | 'gote',
  pieceType: PieceType,
  from = { row: 6, col: 2 },
  to = { row: 5, col: 2 },
  promotion: NormalMoveRecord['promotion'] = 'none'
): NormalMoveRecord {
  return {
    kind: 'move',
    moveNumber,
    player,
    from,
    to,
    pieceType,
    capturedPieceType: null,
    promotion,
    notation: 'テスト手',
  };
}

function createState(history: MoveRecord[]): BoardState {
  const initial = createInitialBoardState();
  const positionSnapshots: PositionSnapshot[] = [];

  for (let historyIndex = 0; historyIndex <= history.length; historyIndex += 1) {
    positionSnapshots.push(
      createPositionSnapshot({
        ...initial,
        history: history.slice(0, historyIndex),
        lastMove: historyIndex === 0 ? null : history[historyIndex - 1],
        moveNumber: historyIndex + 1,
      })
    );
  }

  return {
    ...initial,
    history,
    lastMove: history.at(-1) ?? null,
    moveNumber: history.length + 1,
    positionSnapshots,
  };
}

function setPromotedPiece(
  snapshot: PositionSnapshot,
  coordinate: { row: number; col: number },
  pieceType: PieceType
): void {
  snapshot.squares[coordinate.row][coordinate.col].piece = {
    id: 'promoted-' + pieceType,
    type: pieceType,
    player: 'sente',
    isPromoted: true,
  };
}

function createPromotedPieceState(pieceType: PieceType): BoardState {
  const from = { row: 5, col: 5 };
  const history: MoveRecord[] = [
    createMove(1, 'sente', 'pawn'),
    createMove(2, 'gote', 'pawn', { row: 2, col: 2 }, { row: 3, col: 2 }),
    createMove(3, 'sente', pieceType, from, { row: 4, col: 5 }),
  ];
  const state = createState(history);
  setPromotedPiece(state.positionSnapshots![2], from, pieceType);
  return state;
}

afterEach(() => {
  vi.restoreAllMocks();
  vi.unstubAllGlobals();
  vi.useRealTimers();
});

describe('KIF export', () => {
  it('writes a deterministic KIF 2.0 header with CRLF and a final newline', () => {
    expect(createKifText(createInitialBoardState())).toBe(
      '#KIF version=2.0 encoding=UTF-8\r\n# Generated by Shogi-App\r\n手数----指手---------消費時間--\r\n'
    );
  });

  it.each([
    ['pawn', 'と'],
    ['lance', '成香'],
    ['knight', '成桂'],
    ['silver', '成銀'],
    ['bishop', '馬'],
    ['rook', '龍'],
  ] as const)('uses the promoted %s notation from the preceding snapshot', (pieceType, expectedPiece) => {
    expect(createKifText(createPromotedPieceState(pieceType))).toContain('４五' + expectedPiece + '(46)\r\n');
  });

  it('keeps promotion, non-promotion, and drop notation', () => {
    const history: MoveRecord[] = [
      createMove(1, 'sente', 'bishop', { row: 7, col: 1 }, { row: 1, col: 7 }, 'promote'),
      createMove(2, 'gote', 'bishop', { row: 1, col: 7 }, { row: 7, col: 1 }, 'decline'),
      {
        kind: 'drop',
        moveNumber: 3,
        player: 'sente',
        from: null,
        pieceId: 'pawn-in-hand',
        to: { row: 4, col: 4 },
        pieceType: 'pawn',
        capturedPieceType: null,
        promotion: 'none',
        notation: 'テスト駒打ち',
      },
    ];
    const state = { ...createState(history), positionSnapshots: undefined };
    const kif = createKifText(state);

    expect(kif).toContain('２二角成(88)\r\n');
    expect(kif).toContain('８八角(22)\r\n');
    expect(kif).toContain('５五歩打\r\n');
  });

  it('writes all typed game results without winner lookup for draws', () => {
    const cases: Array<{ result: GameResult; conclusion: string; summary: string }> = [
      { result: { endReason: 'resignation', winner: 'gote', loser: 'sente' }, conclusion: '投了', summary: '後手の勝ち' },
      { result: { endReason: 'checkmate', winner: 'sente', loser: 'gote' }, conclusion: '詰み', summary: '先手の勝ち' },
      { result: { endReason: 'foul_loss', winner: 'gote', loser: 'sente', foulReason: 'perpetual_check_repetition' }, conclusion: '反則勝ち', summary: '後手の勝ち' },
      { result: { endReason: 'repetition', winner: null, loser: null }, conclusion: '千日手', summary: '千日手' },
      { result: { endReason: 'five_hundred_move_jishogi', winner: null, loser: null }, conclusion: '持将棋', summary: '500手規定' },
      { result: { endReason: 'agreed_jishogi_draw', winner: null, loser: null, sentePoints: 24, gotePoints: 24 }, conclusion: '持将棋', summary: '先手24点・後手24点' },
      { result: { endReason: 'agreed_jishogi_point_loss', winner: 'sente', loser: 'gote', sentePoints: 28, gotePoints: 23 }, conclusion: '持将棋', summary: '先手の勝ち' },
      { result: { endReason: 'entering_king_win', winner: 'sente', loser: 'gote' }, conclusion: '入玉勝ち', summary: '先手の勝ち' },
      { result: { endReason: 'entering_king_draw', winner: null, loser: null }, conclusion: '持将棋', summary: '入玉宣言による引き分け' },
      { result: { endReason: 'entering_king_declaration_failure', winner: 'gote', loser: 'sente' }, conclusion: '反則負け', summary: '後手の勝ち' },
    ];

    for (const { result, conclusion, summary } of cases) {
      const state: BoardState = { ...createInitialBoardState(), status: 'ended', result };
      const kif = createKifText(state);
      expect(kif).toContain('   1 ' + conclusion + '\r\n');
      expect(kif).toContain(summary);
    }
  });

  it('exports empty or unfinished games when result is null or undefined', () => {
    const nullResult = { ...createInitialBoardState(), result: null, positionSnapshots: undefined };
    const undefinedResult = { ...createInitialBoardState(), result: undefined, positionSnapshots: undefined };

    expect(createKifText(nullResult)).toBe(createKifText(undefinedResult));
  });

  it('uses 反則負け for strict illegal moves and drops that are absent from legal history', () => {
    const illegalMove = executeMove(
      createInitialBoardState(),
      { row: 6, col: 2 },
      { row: 4, col: 2 },
      { mode: 'strict', proposer: 'shogi_engine' }
    );
    const illegalDrop = executeDrop(
      createInitialBoardState(),
      'missing-piece',
      { row: 4, col: 4 },
      { mode: 'strict', proposer: 'shogi_engine' }
    );

    expect(illegalMove.type).toBe('foul_loss');
    expect(illegalDrop.type).toBe('foul_loss');
    if (illegalMove.type !== 'foul_loss' || illegalDrop.type !== 'foul_loss') return;

    for (const state of [illegalMove.state, illegalDrop.state]) {
      expect(state.moveNumber).toBe(state.history.length + 1);
      expect(createKifText(state)).toContain(
        String(state.history.length + 1).padStart(4, ' ') + ' 反則負け\r\n'
      );
    }
  });

  it('uses 反則勝ち only for perpetual-check repetition after the recorded move', () => {
    const state: BoardState = {
      ...createInitialBoardState(),
      status: 'ended',
      result: {
        endReason: 'foul_loss',
        winner: 'gote',
        loser: 'sente',
        foulReason: 'perpetual_check_repetition',
      },
    };

    expect(createKifText(state)).toContain('   1 反則勝ち\r\n');
  });

  it('rejects a promoted-piece move when its required snapshot is missing', () => {
    const history: MoveRecord[] = [
      createMove(1, 'sente', 'pawn', { row: 6, col: 2 }, { row: 5, col: 2 }, 'promote'),
      createMove(2, 'gote', 'pawn', { row: 2, col: 2 }, { row: 3, col: 2 }),
      createMove(3, 'sente', 'pawn', { row: 5, col: 2 }, { row: 4, col: 2 }),
    ];
    const state = { ...createState(history), positionSnapshots: undefined };

    expect(() => createKifText(state)).toThrow('成駒の表記に必要な局面スナップショット');
  });

  it('rejects inconsistent snapshot history', () => {
    const state = createState([createMove(1, 'sente', 'pawn')]);
    state.positionSnapshots![1].lastMove = null;

    expect(() => createKifText(state)).toThrow('局面スナップショットと指し手履歴が一致しません');
  });

  it('creates a KIF filename matching the JSON record timestamp style', () => {
    expect(createKifFileName(new Date('2026-09-02T03:04:05.678Z'))).toBe(
      'shogi-game-20260902-030405.678Z.kif'
    );
  });

  it('removes the temporary link and revokes the URL after the delayed cleanup', () => {
    vi.useFakeTimers();
    const createObjectURL = vi.fn(() => 'blob:kif');
    const revokeObjectURL = vi.fn();
    const link = document.createElement('a');
    const click = vi.spyOn(link, 'click');
    vi.spyOn(document, 'createElement').mockReturnValue(link);
    vi.stubGlobal('URL', { createObjectURL, revokeObjectURL });

    downloadKifText('KIF', 'game.kif');

    expect(click).toHaveBeenCalledOnce();
    expect(document.body.contains(link)).toBe(false);
    expect(revokeObjectURL).not.toHaveBeenCalled();
    vi.advanceTimersByTime(1_000);
    expect(revokeObjectURL).toHaveBeenCalledWith('blob:kif');
  });

  it('removes the temporary link when clicking the download throws', () => {
    vi.useFakeTimers();
    const createObjectURL = vi.fn(() => 'blob:kif');
    const revokeObjectURL = vi.fn();
    const link = document.createElement('a');
    vi.spyOn(link, 'click').mockImplementation(() => {
      throw new Error('download failed');
    });
    vi.spyOn(document, 'createElement').mockReturnValue(link);
    vi.stubGlobal('URL', { createObjectURL, revokeObjectURL });

    expect(() => downloadKifText('KIF', 'game.kif')).toThrow('download failed');
    expect(document.body.contains(link)).toBe(false);
    vi.advanceTimersByTime(1_000);
    expect(revokeObjectURL).toHaveBeenCalledWith('blob:kif');
  });
});
