import { describe, expect, it, vi } from 'vitest';
import {
  createKifFileName,
  createKifText,
  downloadKifText,
  type BoardState,
  type GameResult,
  type MoveRecord,
} from '../domain/shogi';
import { createInitialBoardState } from '../types/shogi';

function createStateWithHistory(history: MoveRecord[]): BoardState {
  const state = createInitialBoardState();
  return {
    ...state,
    history,
    lastMove: history.at(-1) ?? null,
    moveNumber: history.length + 1,
  };
}

describe('KIF export', () => {
  it('writes a deterministic KIF 2.0 header with CRLF and a final newline', () => {
    expect(createKifText(createInitialBoardState())).toBe(
      '#KIF version=2.0\r\n# Generated by Shogi-App\r\n手数----指手---------消費時間--\r\n',
    );
  });

  it('formats normal, promoted, declined and drop moves in KIF notation', () => {
    const history: MoveRecord[] = [
      { kind: 'move', moveNumber: 1, player: 'sente', from: { row: 6, col: 2 }, to: { row: 5, col: 2 }, pieceType: 'pawn', capturedPieceType: null, promotion: 'none', notation: '▲７六歩' },
      { kind: 'move', moveNumber: 2, player: 'gote', from: { row: 1, col: 7 }, to: { row: 7, col: 1 }, pieceType: 'bishop', capturedPieceType: null, promotion: 'decline', notation: '△２八角不成' },
      { kind: 'drop', moveNumber: 3, player: 'sente', from: null, pieceId: 'piece-1', to: { row: 4, col: 4 }, pieceType: 'pawn', capturedPieceType: null, promotion: 'none', notation: '▲５五歩打' },
      { kind: 'move', moveNumber: 4, player: 'gote', from: { row: 7, col: 1 }, to: { row: 1, col: 7 }, pieceType: 'bishop', capturedPieceType: null, promotion: 'promote', notation: '△２二角成' },
    ];

    const kif = createKifText(createStateWithHistory(history));
    expect(kif).toContain('   1 ７六歩(77)\r\n');
    expect(kif).toContain('   2 ８八角不成(22)\r\n');
    expect(kif).toContain('   3 ５五歩打\r\n');
    expect(kif).toContain('   4 ２二角成(88)\r\n');
  });

  it.each([
    [{ type: 'resignation', loser: 'sente' }, '投了'],
    [{ type: 'checkmate', loser: 'gote' }, '詰み'],
    [{ type: 'foul_loss', loser: 'sente' }, '反則勝ち'],
    [{ type: 'repetition' }, '千日手'],
    [{ type: 'five_hundred_move_jishogi' }, '持将棋'],
    [{ type: 'agreed_jishogi_draw' }, '持将棋'],
    [{ type: 'agreed_jishogi_point_loss', loser: 'gote' }, '持将棋'],
    [{ type: 'entering_king_win', winner: 'sente' }, '入玉勝ち'],
    [{ type: 'entering_king_draw' }, '入玉'],
    [{ type: 'entering_king_declaration_failure', loser: 'sente' }, '入玉宣言失敗'],
  ] as [unknown, string][])('converts each result to a KIF conclusion', (result, conclusion) => {
    const state = {
      ...createInitialBoardState(),
      status: 'ended' as const,
      result: result as GameResult,
    };
    expect(createKifText(state)).toContain('   1 ' + conclusion + '\r\n');
  });

  it('rejects coordinates outside the board', () => {
    const state = createStateWithHistory([
      { kind: 'move', moveNumber: 1, player: 'sente', from: { row: 6, col: 2 }, to: { row: 9, col: 2 }, pieceType: 'pawn', capturedPieceType: null, promotion: 'none', notation: 'invalid' },
    ]);
    expect(() => createKifText(state)).toThrow('盤上の座標');
  });

  it('creates a .kif file name and releases the download URL', () => {
    expect(createKifFileName(new Date('2026-09-02T03:04:05.678Z'))).toBe('shogi-game-20260902T030405-678Z.kif');
    const createObjectURL = vi.fn(() => 'blob:kif');
    const revokeObjectURL = vi.fn();
    const click = vi.fn();
    const createElement = vi.spyOn(document, 'createElement').mockReturnValue({ click } as HTMLAnchorElement);
    vi.stubGlobal('URL', { createObjectURL, revokeObjectURL });

    downloadKifText('KIF', 'game.kif');

    expect(createObjectURL).toHaveBeenCalledOnce();
    expect(click).toHaveBeenCalledOnce();
    expect(revokeObjectURL).toHaveBeenCalledWith('blob:kif');
    createElement.mockRestore();
    vi.unstubAllGlobals();
  });
});
